language: node_js
node_js:
  - "8"

script:
  - npm run test
  - npm run report-coverage
#  - codecov ./coverage/cobertura-coverage.xml

#before_script:
#  - npm run lint

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
